# Generated by Django 2.2.6 on 2019-11-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='name',
            new_name='ref',
        ),
    ]
