# Generated by Django 2.2.6 on 2019-11-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.TextField()),
                ('delivery_cost', models.IntegerField()),
                ('absolute', models.BooleanField(default=False)),
            ],
        ),
    ]
