# Generated by Django 2.2.6 on 2019-11-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deliver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryqueue',
            old_name='absolute',
            new_name='done',
        ),
    ]
